#!/bin/sh
#
SCRIPTDIR=$(cd $(dirname $0) && pwd)

if [ ! -d $SCRIPTDIR/venv ]; then
  echo "Please run setup.sh first."
  exit 1
fi

export PYTHONPATH=$PYTHONPATH:$SCRIPTDIR
cd $SCRIPTDIR
. $SCRIPTDIR/venv/bin/activate
python3 -W ignore $SCRIPTDIR/cb_perf.py $@
