#!/bin/sh
##
SCRIPTDIR=$(cd $(dirname $0) && pwd)
PKGDIR=$(dirname $SCRIPTDIR)
VENV="venv"

case "$1" in
  -v )
    VENV=$2
    shift 2
    ;;
esac

if [ ! -d $PKGDIR/$VENV ]; then
  echo "Please run setup.sh first."
  exit 1
fi

. $PKGDIR/$VENV/bin/activate

cd $PKGDIR
python3 -W ignore test/f_test.py $@

RETURN_CODE=$?
if [ $RETURN_CODE -ne 0 ]; then
  echo "Test set exited with an error code $RETURN_CODE"
fi
